// packages/playground/src/components/Add_round.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M12 6v12m6-6H6"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "addRound",
} as DefineComponent;
</script>

// packages/playground/src/react/components/AddRound.tsx
import React, { SVGProps } from "react";

export function AddRound(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12 6v12m6-6H6"
            />
        </svg>
    );
}
export default AddRound;
