// packages/playground/src/components/Add_round_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path fill="none" stroke="currentColor" d="M12 6v12m6-6H6" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "addRoundLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/AddRoundLight.tsx
import React, { SVGProps } from "react";

export function AddRoundLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12 6v12m6-6H6"
            />
        </svg>
    );
}
export default AddRoundLight;
