// packages/playground/src/components/Arrow_drop_down_big.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="M11.18 15.83 6.543 9.203C5.892 8.275 6.556 7 7.689 7h8.622c1.133 0 1.796 1.275 1.147 2.203l-4.639 6.627a1 1 0 0 1-1.638 0Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "arrowDropDownBig",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ArrowDropDownBig.tsx
import React, { SVGProps } from "react";

export function ArrowDropDownBig(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="M11.1808 15.8297 6.542 9.2028C5.8925 8.275 6.5563 7 7.689 7h8.6221c1.1326 0 1.7964 1.275 1.1469 2.2028l-4.6388 6.6269c-.3981.5687-1.2403.5687-1.6384 0Z"
            />
        </svg>
    );
}
export default ArrowDropDownBig;
