// packages/playground/src/components/Arrow_drop_left.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="m7.293 11.795 8.448-5.914A.8.8 0 0 1 17 6.536v10.927a.8.8 0 0 1-1.259.656l-8.448-5.914a.25.25 0 0 1 0-.41Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "arrowDropLeft",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ArrowDropLeft.tsx
import React, { SVGProps } from "react";

export function ArrowDropLeft(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m9.2305 11.8079 4.4574-3.7144C14.2089 7.6592 15 8.0298 15 8.708v6.584c0 .6782-.7911 1.0488-1.3121.6145l-4.4574-3.7144a.25.25 0 0 1 0-.3842Z"
            />
        </svg>
    );
}
export default ArrowDropLeft;
