// packages/playground/src/components/Box_refresh_right_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="m14 16 .354-.354.353.354-.353.354L14 16Zm-3.646-4.354 4 4-.708.708-4-4 .708-.708Zm4 4.708-4 4-.708-.708 4-4 .708.708Z"
        />
        <path
            stroke="currentColor"
            d="M20 13.5V10a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h7"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "boxRefreshRightLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/BoxRefreshRightLight.tsx
import React, { SVGProps } from "react";

export function BoxRefreshRightLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m14 16 .3536-.3536.3535.3536-.3535.3536L14 16Zm-3.6464-4.3536 4 4-.7072.7072-4-4 .7072-.7072Zm4 4.7072-4 4-.7072-.7072 4-4 .7072.7072Z"
            />
            <path
                stroke="currentColor"
                d="M20 13.5V10c0-1.1046-.8954-2-2-2H6c-1.1046 0-2 .8954-2 2v4c0 1.1046.8954 2 2 2h7"
            />
        </svg>
    );
}
export default BoxRefreshRightLight;
