// packages/playground/src/components/Cancel_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle
            cx="12"
            cy="12"
            r="9"
            stroke="currentColor"
            stroke-opacity=".24"
            stroke-width="1.2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            d="M16 16 8 8"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "cancelDuotoneLine",
} as DefineComponent;
</script>

// packages/playground/src/react/components/CancelDuotoneLine.tsx
import React, { SVGProps } from "react";

export function CancelDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" stroke="currentColor" />
            <path fill="currentColor" stroke="currentColor" d="M16 16 8 8" />
        </svg>
    );
}
export default CancelDuotoneLine;
