// packages/playground/src/components/Chart_alt_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            d="m17 9-3.044 4.566a1 1 0 0 1-1.727-.107l-.458-.918a1 1 0 0 0-1.727-.107L7 17"
        />
        <rect width="18" height="18" x="3" y="3" stroke="currentColor" rx="2" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "chartAltLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ChartAltLight.tsx
import React, { SVGProps } from "react";

export function ChartAltLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m17 9-3.0442 4.5662c-.4259.6389-1.383.5793-1.7264-.1075l-.4588-.9174c-.3434-.6868-1.3005-.7464-1.7264-.1075L7 17"
                strokeLinejoin="round"
            />
            <rect
                width="18"
                height="18"
                x="3"
                y="3"
                stroke="currentColor"
                rx="2"
            />
        </svg>
    );
}
export default ChartAltLight;
