// packages/playground/src/components/Chart_alt_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <rect
            width="18"
            height="18"
            x="3"
            y="3"
            fill="currentColor"
            fill-opacity=".24"
            rx="2"
        />
        <path
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="1.2"
            d="m18 8-3.895 4.87a.15.15 0 0 1-.224.012l-2.765-2.766a.15.15 0 0 0-.221.01L6 16"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "chartAltDuotone",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ChartAltDuotone.tsx
import React, { SVGProps } from "react";

export function ChartAltDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <rect
                width="18"
                height="18"
                x="3"
                y="3"
                fill="currentColor"
                rx="2"
            />
            <path
                stroke="currentColor"
                d="m18 8-3.8953 4.8691a.15.15 0 0 1-.2232.0124l-2.7654-2.7654a.15.15 0 0 0-.2213.0101L6 16"
            />
        </svg>
    );
}
export default ChartAltDuotone;
