// packages/playground/src/components/Chield_alt_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-opacity=".24"
            stroke="currentColor"
            stroke-width="1.2"
            d="M16.8 16.4 15 17.75a5 5 0 0 1-6 0L7.2 16.4A8 8 0 0 1 4 10V6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v4a8 8 0 0 1-3.2 6.4Z"
        />
        <circle cx="12" cy="10" r="1" fill="currentColor" />
        <circle cx="9" cy="10" r="1" fill="currentColor" />
        <circle cx="15" cy="10" r="1" fill="currentColor" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "chieldAltDuotoneLine",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ChieldAltDuotoneLine.tsx
import React, { SVGProps } from "react";

export function ChieldAltDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M16.8 16.4 15 17.75c-1.7778 1.3333-4.2222 1.3333-6 0L7.2 16.4A7.9999 7.9999 0 0 1 4 10V6c0-1.1046.8954-2 2-2h12c1.1046 0 2 .8954 2 2v4a8 8 0 0 1-3.2 6.4Z"
            />
            <circle cx="12" cy="10" r="1" fill="currentColor" />
            <circle cx="9" cy="10" r="1" fill="currentColor" />
            <circle cx="15" cy="10" r="1" fill="currentColor" />
        </svg>
    );
}
export default ChieldAltDuotoneLine;
