// packages/playground/src/components/Chield_alt_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-opacity=".24"
            d="m15.545 4.52 2.849 1.22a1 1 0 0 1 .606.92v6.252a6 6 0 0 1-2.513 4.883l-3.906 2.79a1 1 0 0 1-1.162 0l-3.906-2.79A6 6 0 0 1 5 12.912V6.66a1 1 0 0 1 .606-.919l2.849-1.22a9 9 0 0 1 7.09 0Z"
        />
        <circle cx="12" cy="10.5" r=".5" fill="currentColor" />
        <circle cx="9.5" cy="10.5" r=".5" fill="currentColor" />
        <circle cx="14.5" cy="10.5" r=".5" fill="currentColor" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "chieldAltDuotone",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ChieldAltDuotone.tsx
import React, { SVGProps } from "react";

export function ChieldAltDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m15.5453 4.5194 2.8486 1.2208A1 1 0 0 1 19 6.6594v6.2529a6 6 0 0 1-2.5126 4.8824l-3.9062 2.7901a.9997.9997 0 0 1-1.1624 0l-3.9062-2.7901A6 6 0 0 1 5 12.9123V6.6594a1 1 0 0 1 .606-.9192l2.8487-1.2208a9 9 0 0 1 7.0906 0Z"
            />
            <circle cx="12" cy="10.5" r=".5" fill="currentColor" />
            <circle cx="9.5" cy="10.5" r=".5" fill="currentColor" />
            <circle cx="14.5" cy="10.5" r=".5" fill="currentColor" />
        </svg>
    );
}
export default ChieldAltDuotone;
