// packages/playground/src/components/Close_round.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="M18 6 6 18M6 6l12 12"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "closeRound",
} as DefineComponent;
</script>

// packages/playground/src/react/components/CloseRound.tsx
import React, { SVGProps } from "react";

export function CloseRound(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M18 6 6 18M6 6l12 12"
            />
        </svg>
    );
}
export default CloseRound;
