// packages/playground/src/components/Data_bank.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            stroke="currentColor"
            stroke-width="2"
            d="M6 14h12a3 3 0 1 1 0 6H6a3 3 0 1 1 0-6Z"
        />
        <path
            stroke="currentColor"
            stroke-width="2"
            d="M3 17c0-1.41 1.491-7.294 2.371-10.642.22-.835.329-1.252.571-1.57a2.014 2.014 0 0 1 .823-.635C7.134 4 7.57 4 8.445 4h7.11c.875 0 1.312 0 1.68.153.323.135.611.357.823.635.242.318.352.735.571 1.57C19.51 9.706 21 15.59 21 17"
        />
        <rect width="2" height="2" x="17" y="16" fill="currentColor" rx="1" />
        <rect width="4" height="2" x="5" y="16" fill="currentColor" rx="1" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "dataBank",
} as DefineComponent;
</script>

// packages/playground/src/react/components/DataBank.tsx
import React, { SVGProps } from "react";

export function DataBank(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                stroke="currentColor"
                d="M6 14h12c1.6569 0 3 1.3431 3 3s-1.3431 3-3 3H6c-1.6569 0-3-1.3431-3-3s1.3431-3 3-3Z"
            />
            <path
                stroke="currentColor"
                d="M3 17c0-1.4101 1.4912-7.2938 2.371-10.6421.2193-.8349.329-1.2524.571-1.57a2.0138 2.0138 0 0 1 .8228-.6345C7.1335 4 7.5704 4 8.4442 4h7.1117c.8737 0 1.3106 0 1.6793.1534.3231.1343.6108.3562.8228.6345.242.3176.3517.7351.5711 1.57C19.5088 9.7062 21 15.5899 21 17"
            />
            <rect
                width="2"
                height="2"
                x="17"
                y="16"
                fill="currentColor"
                rx="1"
            />
            <rect
                width="4"
                height="2"
                x="5"
                y="16"
                fill="currentColor"
                rx="1"
            />
        </svg>
    );
}
export default DataBank;
