// packages/playground/src/components/Done.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="m5 14 4 3 9-11"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "done",
} as DefineComponent;
</script>

// packages/playground/src/react/components/Done.tsx
import React, { SVGProps } from "react";

export function Done(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m5 14 4 3 9-11"
            />
        </svg>
    );
}
export default Done;
