// packages/playground/src/components/Done_round_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="m5 14 3.233 2.425a1 1 0 0 0 1.374-.167L18 6"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneRoundLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/DoneRoundLight.tsx
import React, { SVGProps } from "react";

export function DoneRoundLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m5 14 3.233 2.4248a1 1 0 0 0 1.374-.1667L18 6"
            />
        </svg>
    );
}
export default DoneRoundLight;
