// packages/playground/src/components/Done_round_fill.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M19.548 7.266a2 2 0 1 0-3.096-2.532L8.666 14.25 6.2 12.4a2 2 0 0 0-2.4 3.2l3.233 2.425a3 3 0 0 0 4.122-.5l8.393-10.258Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneRoundFill",
} as DefineComponent;
</script>

// packages/playground/src/react/components/DoneRoundFill.tsx
import React, { SVGProps } from "react";

export function DoneRoundFill(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M19.5479 7.2665c.6995-.8549.5735-2.115-.2814-2.8144-.8549-.6994-2.115-.5734-2.8144.2815l-7.786 9.5161L6.2 12.4c-.8837-.6627-2.1373-.4836-2.8.4-.6627.8837-.4836 2.1373.4 2.8l3.233 2.4248c1.2862.9646 3.104.744 4.122-.5002l8.3929-10.258Z"
            />
        </svg>
    );
}
export default DoneRoundFill;
