// packages/playground/src/components/Done_all_alt_round_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            stroke="currentColor"
            d="m2 14 3.233 2.425a1 1 0 0 0 1.374-.167L15 6"
        />
        <path
            fill="currentColor"
            fill-rule="evenodd"
            d="m10.191 15.393 1.724 1.38a1.5 1.5 0 0 0 2.098-.222l8.374-10.234a.5.5 0 0 0-.774-.634l-8.374 10.235a.5.5 0 0 1-.699.074l-1.716-1.373-.633.774Z"
            clip-rule="evenodd"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneAllAltRoundLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/DoneAllAltRoundLight.tsx
import React, { SVGProps } from "react";

export function DoneAllAltRoundLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                stroke="currentColor"
                d="m2 14 3.233 2.4248a1 1 0 0 0 1.374-.1667L15 6"
            />
            <path
                fill="currentColor"
                d="m10.191 15.3932 1.7243 1.3794c.6419.5135 1.5775.4147 2.098-.2215L22.387 6.3166a.5.5 0 0 0-.774-.6332l-8.3737 10.2345a.4999.4999 0 0 1-.6993.0738l-1.7157-1.3725-.6333.774Z"
            />
        </svg>
    );
}
export default DoneAllAltRoundLight;
