// packages/playground/src/components/Expand_down_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="m12 15 .354.354-.354.353-.354-.353L12 15Zm6.354-5.646-6 6-.708-.708 6-6 .708.708Zm-6.708 6-6-6 .708-.708 6 6-.708.708Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "expandDownLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ExpandDownLight.tsx
import React, { SVGProps } from "react";

export function ExpandDownLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m12 15 .3536.3536-.3536.3535-.3536-.3535L12 15Zm6.3536-5.6464-6 6-.7072-.7072 6-6 .7072.7072Zm-6.7072 6-6-6 .7072-.7072 6 6-.7072.7072Z"
            />
        </svg>
    );
}
export default ExpandDownLight;
