// packages/playground/src/components/Expand_up_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="m12 9 .354-.354L12 8.293l-.354.354L12 9Zm6.354 5.646-6-6-.708.708 6 6 .708-.708Zm-6.708-6-6 6 .708.708 6-6-.708-.708Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "expandUpLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ExpandUpLight.tsx
import React, { SVGProps } from "react";

export function ExpandUpLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m12 9 .3536-.3536L12 8.293l-.3536.3536L12 9Zm6.3536 5.6464-6-6-.7072.7072 6 6 .7072-.7072Zm-6.7072-6-6 6 .7072.7072 6-6-.7072-.7072Z"
            />
        </svg>
    );
}
export default ExpandUpLight;
