// packages/playground/src/components/External.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M14 4h6m0 0v6m0-6-8 8"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M11 5H7a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "external",
} as DefineComponent;
</script>

// packages/playground/src/react/components/External.tsx
import React, { SVGProps } from "react";

export function External(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M15 3.5h5.5m0 0V9m0-5.5-8 8"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M11.5 5.5h-4c-1.1046 0-2 .8954-2 2v9c0 1.1046.8954 2 2 2h9c1.1046 0 2-.8954 2-2v-4"
            />
        </svg>
    );
}
export default External;
