// packages/playground/src/components/Line_up.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="m21 6-5.293 5.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 0-1.414 0L7 14"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M3 3v14.8c0 1.12 0 1.68.218 2.108a2 2 0 0 0 .874.874C4.52 21 5.08 21 6.2 21H21"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "lineUp",
} as DefineComponent;
</script>

// packages/playground/src/react/components/LineUp.tsx
import React, { SVGProps } from "react";

export function LineUp(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m21 6-5.2929 5.2929c-.3905.3905-1.0237.3905-1.4142 0l-1.5858-1.5858c-.3905-.3905-1.0237-.3905-1.4142 0L7 14"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M3 3v14.8c0 1.1201 0 1.6802.218 2.108.1917.3763.4977.6823.874.874C4.5198 21 5.08 21 6.2 21H21"
            />
        </svg>
    );
}
export default LineUp;
