// packages/playground/src/components/Link.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="M10 16H7a4 4 0 0 1 0-8h3m6 4H8m6 4h3a4 4 0 0 0 0-8h-3"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "link",
} as DefineComponent;
</script>

// packages/playground/src/react/components/Link.tsx
import React, { SVGProps } from "react";

export function Link(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M10 16H7c-2.2091 0-4-1.7909-4-4 0-2.2091 1.7909-4 4-4h3m6 4H8m6 4h3c2.2091 0 4-1.7909 4-4 0-2.2091-1.7909-4-4-4h-3"
                strokeLinejoin="round"
                strokeWidth="2"
            />
        </svg>
    );
}
export default Link;
