// packages/playground/src/components/Materials_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            d="m3 7 7-4 11 4M3 7v5l11 4 7-4V7M3 7l11 4 7-4"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            d="M3 12v5l11 4 7-4v-5"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "materialsLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/MaterialsLight.tsx
import React, { SVGProps } from "react";

export function MaterialsLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m3 7 7-4 11 4M3 7v5l11 4 7-4V7M3 7l11 4 7-4"
                strokeLinejoin="round"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M3 12v5l11 4 7-4v-5"
                strokeLinejoin="round"
            />
        </svg>
    );
}
export default MaterialsLight;
