// packages/playground/src/components/On_button_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M6.343 6.343a8 8 0 1 0 11.314 0M12 8V4"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "onButtonLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/OnButtonLight.tsx
import React, { SVGProps } from "react";

export function OnButtonLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M6.3431 6.3431a8 8 0 1 0 11.3138 0M12 8V4"
            />
        </svg>
    );
}
export default OnButtonLight;
