// packages/playground/src/components/Paper_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M18 3a3 3 0 0 1 3 3v2.143c0 .334 0 .501-.077.623a.5.5 0 0 1-.157.158C20.644 9 20.477 9 20.143 9H15m3-6a3 3 0 0 0-3 3v3m3-6H7c-1.886 0-2.828 0-3.414.586C3 4.172 3 5.114 3 7v14l3-1 3 1 3-1 3 1V9"
        />
        <path fill="none" stroke="currentColor" d="M7 7h4m-3 4H7m0 4h3" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "paperLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/PaperLight.tsx
import React, { SVGProps } from "react";

export function PaperLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M18 3c1.6569 0 3 1.3431 3 3v2.143c0 .334 0 .5012-.0766.6231a.5005.5005 0 0 1-.1574.1574C20.644 9 20.477 9 20.1429 9H15m3-6c-1.6569 0-3 1.3431-3 3v3m3-6H7c-1.8856 0-2.8284 0-3.4142.5858C3 4.1716 3 5.1144 3 7v14l3-1 3 1 3-1 3 1V9"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M7 7h4m-3 4H7m0 4h3"
            />
        </svg>
    );
}
export default PaperLight;
