// packages/playground/src/components/Question_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" stroke="currentColor" />
        <circle cx="12" cy="18" r=".5" fill="currentColor" />
        <path
            stroke="currentColor"
            d="M12 16v-.857c0-.714.357-1.381.951-1.777l.599-.4a3.257 3.257 0 0 0 1.45-2.71V10a3 3 0 1 0-6 0"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "questionLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/QuestionLight.tsx
import React, { SVGProps } from "react";

export function QuestionLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" stroke="currentColor" />
            <circle cx="12" cy="18" r=".5" fill="currentColor" />
            <path
                stroke="currentColor"
                d="M12 16v-.8568c0-.7142.357-1.3812.9512-1.7773l.5985-.399A3.257 3.257 0 0 0 15 10.2569V10c0-1.6569-1.3431-3-3-3s-3 1.3431-3 3"
            />
        </svg>
    );
}
export default QuestionLight;
