// packages/playground/src/components/Remove_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity=".24" />
        <path stroke="currentColor" stroke-width="1.2" d="M8 12h8" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "removeDuotone",
} as DefineComponent;
</script>

// packages/playground/src/react/components/RemoveDuotone.tsx
import React, { SVGProps } from "react";

export function RemoveDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" fill="currentColor" />
            <path stroke="currentColor" d="M8 12h8" />
        </svg>
    );
}
export default RemoveDuotone;
