// packages/playground/src/components/Search_fill.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path fill="currentColor" d="M18 11a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z" />
        <path stroke="currentColor" stroke-width="2" d="m20 20-2-2" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "searchFill",
} as DefineComponent;
</script>

// packages/playground/src/react/components/SearchFill.tsx
import React, { SVGProps } from "react";

export function SearchFill(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="M18 11c0 3.866-3.134 7-7 7s-7-3.134-7-7 3.134-7 7-7 7 3.134 7 7Z"
            />
            <path stroke="currentColor" d="m20 20-2-2" />
        </svg>
    );
}
export default SearchFill;
