// packages/playground/src/components/Stop_and_play_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            d="M11.427 11.126 4.594 7.33A.4.4 0 0 0 4 7.68v8.64a.4.4 0 0 0 .594.35l6.833-3.796a1 1 0 0 0 0-1.748Z"
        />
        <path fill="none" stroke="currentColor" d="M16 17V7m4 10V7" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "stopAndPlayLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/StopAndPlayLight.tsx
import React, { SVGProps } from "react";

export function StopAndPlayLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M11.4265 11.1258 4.5943 7.3301C4.3276 7.1821 4 7.3748 4 7.6798v8.6404c0 .305.3277.4978.5943.3497l6.8322-3.7957c.6858-.381.6858-1.3674 0-1.7484Z"
                strokeLinejoin="round"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M16 17V7m4 10V7"
            />
        </svg>
    );
}
export default StopAndPlayLight;
