// packages/playground/src/components/Transger_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M13 17H9v2.588a.2.2 0 0 1-.324.158L2 14.5l6.676-5.246A.2.2 0 0 1 9 9.412V12h6"
        />
        <path
            fill="none"
            stroke="currentColor"
            d="M11 7h4V4.412a.2.2 0 0 1 .324-.158L22 9.5l-6.676 5.246a.2.2 0 0 1-.324-.158V12H9"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "transgerLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/TransgerLight.tsx
import React, { SVGProps } from "react";

export function TransgerLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M13 17H9v2.5885c0 .1669-.1923.2604-.3236.1573L2 14.5l6.6764-5.2458c.1313-.103.3236-.0096.3236.1573V12h6"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M11 7h4V4.4115c0-.1669.1923-.2604.3236-.1573L22 9.5l-6.6764 5.2458c-.1313.1031-.3236.0096-.3236-.1573V12H9"
            />
        </svg>
    );
}
export default TransgerLight;
