// packages/playground/src/components/User_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="8" r="4" fill="currentColor" />
        <path
            fill="currentColor"
            fill-opacity=".24"
            fill-rule="evenodd"
            d="M12 13c-3.67 0-6.68 2.42-6.976 5.5-.026.275.2.5.476.5h13a.465.465 0 0 0 .476-.5C18.68 15.42 15.67 13 12 13Z"
            clip-rule="evenodd"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "userDuotone",
} as DefineComponent;
</script>

// packages/playground/src/react/components/UserDuotone.tsx
import React, { SVGProps } from "react";

export function UserDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="8" r="4" fill="currentColor" />
            <path
                fill="currentColor"
                d="M12 13c-3.6697 0-6.6798 2.4204-6.976 5.5004-.0265.2749.1999.4996.476.4996h13c.2762 0 .5025-.2247.4761-.4996C18.6799 15.4204 15.6697 13 12 13Z"
            />
        </svg>
    );
}
export default UserDuotone;
