// packages/playground/src/components/Video_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            d="M16.211 11.106 9.737 7.868A1.2 1.2 0 0 0 8 8.942v6.116a1.2 1.2 0 0 0 1.737 1.074l6.474-3.238a1 1 0 0 0 0-1.788Z"
        />
        <circle cx="12" cy="12" r="9" stroke="currentColor" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "videoLight",
} as DefineComponent;
</script>

// packages/playground/src/react/components/VideoLight.tsx
import React, { SVGProps } from "react";

export function VideoLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M16.2111 11.1056 9.7367 7.8683C8.9387 7.4693 8 8.0496 8 8.9416v6.1168c0 .892.9388 1.4722 1.7367 1.0733l6.4744-3.2373c.7371-.3685.7371-1.4203 0-1.7888Z"
                strokeLinejoin="round"
            />
            <circle cx="12" cy="12" r="9" stroke="currentColor" />
        </svg>
    );
}
export default VideoLight;
