// packages/playground/src/components/View_horizont.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M11.978 7.834a9 9 0 0 1-.13 8.57"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M14 5c-2.814 2.814-10.029 6.509-10.911 6.955a.05.05 0 0 0 0 .09C3.97 12.49 11.186 16.185 14 19m2-7h5m-5-3 5-2m-5 8 5 2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M11.794 7.5a9 9 0 0 1 .234 8.568"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M12.518 13.931a2 2 0 0 1-1.736-.345 2 2 0 0 1 0-3.173 2 2 0 0 1 1.736-.345"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "viewHorizont",
} as DefineComponent;
</script>

// packages/playground/src/react/components/ViewHorizont.tsx
import React, { SVGProps } from "react";

export function ViewHorizont(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M11.9776 7.8336a9.0009 9.0009 0 0 1-.1287 8.5703"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M14 5c-2.8143 2.8143-10.0286 6.5086-10.9111 6.9552a.0502.0502 0 0 0 0 .0896C3.9714 12.4914 11.1857 16.1857 14 19m2-7h5m-5-3 5-2m-5 8 5 2"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M11.794 7.4996a8.9995 8.9995 0 0 1 .2343 8.5681"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12.5176 13.9315a2.0006 2.0006 0 0 1-1.7351-.3452 1.9997 1.9997 0 0 1 0-3.1734 2.0002 2.0002 0 0 1 1.7351-.3451"
            />
        </svg>
    );
}
export default ViewHorizont;
