// packages/playground/src/components/Watch.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="6" stroke="currentColor" stroke-width="2" />
        <path
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="m8.5 7 .407-3.255A.85.85 0 0 1 9.75 3h4.5a.85.85 0 0 1 .843.745L15.5 7m-7 10 .407 3.255A.85.85 0 0 0 9.75 21h4.5a.85.85 0 0 0 .843-.745L15.5 17"
        />
        <path
            fill="currentColor"
            d="M18.15 11h-.65v2h.65a.85.85 0 0 0 .85-.85v-.3a.85.85 0 0 0-.85-.85Z"
        />
        <path stroke="currentColor" stroke-width="2" d="m12 12-1-3m1 3 2.5 1" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "watch",
} as DefineComponent;
</script>

// packages/playground/src/react/components/Watch.tsx
import React, { SVGProps } from "react";

export function Watch(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <rect
                width="14"
                height="12"
                x="5"
                y="5"
                stroke="currentColor"
                rx="3"
            />
            <path
                fill="currentColor"
                d="M8 4c0-.9428 0-1.4142.2929-1.7071C8.5858 2 9.0572 2 10 2h4c.9428 0 1.4142 0 1.7071.2929C16 2.5858 16 3.0572 16 4v1H8V4Zm0 16c0 .9428 0 1.4142.2929 1.7071C8.5858 22 9.0572 22 10 22h4c.9428 0 1.4142 0 1.7071-.2929C16 21.4142 16 20.9428 16 20v-3H8v3Z"
            />
        </svg>
    );
}
export default Watch;
