// packages/playground/src/react/components/AddDuotoneLine.tsx
import React, { SVGProps } from "react";

export function AddDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="8.4" stroke="currentColor" />
            <path fill="currentColor" stroke="currentColor" d="M12 8v8m4-4H8" />
        </svg>
    );
}
export default AddDuotoneLine;

// packages/playground/src/components/Add_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle
            cx="12"
            cy="12"
            r="8.4"
            stroke="currentColor"
            stroke-opacity=".24"
            stroke-width="1.2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            d="M12 8v8m4-4H8"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "addDuotoneLine",
} as DefineComponent;
</script>
