// packages/playground/src/react/components/BoxRefreshAltRightLight.tsx
import React, { SVGProps } from "react";

export function BoxRefreshAltRightLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m16 16 .3536-.3536.3535.3536-.3535.3536L16 16Zm-3.6464-4.3536 4 4-.7072.7072-4-4 .7072-.7072Zm4 4.7072-4 4-.7072-.7072 4-4 .7072.7072Z"
            />
            <path
                stroke="currentColor"
                d="M13 8h4m-1 8H8c-2.2091 0-4-1.7909-4-4 0-2.2091 1.7909-4 4-4h1"
            />
        </svg>
    );
}
export default BoxRefreshAltRightLight;

// packages/playground/src/components/Box_refresh_alt_right_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            d="m16 16 .354-.354.353.354-.353.354L16 16Zm-3.646-4.354 4 4-.708.708-4-4 .708-.708Zm4 4.708-4 4-.708-.708 4-4 .708.708Z"
        />
        <path stroke="currentColor" d="M13 8h4m-1 8H8a4 4 0 0 1 0-8h1" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "boxRefreshAltRightLight",
} as DefineComponent;
</script>
