// packages/playground/src/react/components/Calendar.tsx
import React, { SVGProps } from "react";

export function Calendar(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <rect
                width="18"
                height="15"
                x="3"
                y="6"
                stroke="currentColor"
                rx="2"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M4 11h16M9 16h6M8 3v4m8-4v4"
            />
        </svg>
    );
}
export default Calendar;

// packages/playground/src/components/Calendar.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <rect
            width="18"
            height="15"
            x="3"
            y="6"
            stroke="currentColor"
            stroke-width="2"
            rx="2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M4 11h16M9 16h6M8 3v4m8-4v4"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "calendar",
} as DefineComponent;
</script>
