// packages/playground/src/react/components/CancelLight.tsx
import React, { SVGProps } from "react";

export function CancelLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" stroke="currentColor" />
            <path fill="currentColor" stroke="currentColor" d="M18 18 6 6" />
        </svg>
    );
}
export default CancelLight;

// packages/playground/src/components/Cancel_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" stroke="currentColor" />
        <path fill="none" stroke="currentColor" d="M18 18 6 6" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "cancelLight",
} as DefineComponent;
</script>
