// packages/playground/src/react/components/Chart.tsx
import React, { SVGProps } from "react";

export function Chart(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M8 10v6m4-4v4m4-8v8"
            />
            <rect
                width="18"
                height="16"
                x="3"
                y="4"
                stroke="currentColor"
                rx="2"
            />
        </svg>
    );
}
export default Chart;

// packages/playground/src/components/Chart.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="M8 10v6m4-4v4m4-8v8"
        />
        <rect
            width="18"
            height="16"
            x="3"
            y="4"
            stroke="currentColor"
            stroke-width="2"
            rx="2"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "chart",
} as DefineComponent;
</script>
