// packages/playground/src/react/components/CloseRoundDuotone.tsx
import React, { SVGProps } from "react";

export function CloseRoundDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" fill="currentColor" />
            <path stroke="currentColor" d="m16 8-8 8m0-8 8 8" />
        </svg>
    );
}
export default CloseRoundDuotone;

// packages/playground/src/components/Close_round_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity=".24" />
        <path
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="1.2"
            d="m16 8-8 8m0-8 8 8"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "closeRoundDuotone",
} as DefineComponent;
</script>
