// packages/playground/src/react/components/DatabaseLight.tsx
import React, { SVGProps } from "react";

export function DatabaseLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <ellipse cx="12" cy="7" stroke="currentColor" rx="7" ry="3" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M5 13v4c0 1.6569 3.134 3 7 3s7-1.3431 7-3v-4"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M5 7v5c0 1.6569 3.134 3 7 3s7-1.3431 7-3V7"
            />
        </svg>
    );
}
export default DatabaseLight;

// packages/playground/src/components/Database_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <ellipse cx="12" cy="6" stroke="currentColor" rx="7" ry="3" />
        <path
            fill="none"
            stroke="currentColor"
            d="M19 18c0 .394-.181.784-.533 1.148-.352.364-.867.695-1.517.973-.65.279-1.422.5-2.271.65-.85.151-1.76.229-2.679.229-.92 0-1.83-.078-2.679-.228-.85-.151-1.62-.372-2.27-.65-.65-.28-1.166-.61-1.518-.974C5.18 18.784 5 18.394 5 18M19 6v12M5 6v12"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "databaseLight",
} as DefineComponent;
</script>
