// packages/playground/src/react/components/DateRangeDuotoneLine.tsx
import React, { SVGProps } from "react";

export function DateRangeDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path fill="currentColor" stroke="currentColor" d="M17 3v4M7 3v4" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M3 10c0-1.8856 0-2.8284.5858-3.4142C4.1716 6 5.1144 6 7 6h10c1.8856 0 2.8284 0 3.4142.5858C21 7.1716 21 8.1144 21 10v1H3v-1Z"
            />
            <rect
                width="18"
                height="15"
                x="3"
                y="6"
                stroke="currentColor"
                rx="2"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M6 15h4m4 0h4M6 18h4m4 0h4"
            />
        </svg>
    );
}
export default DateRangeDuotoneLine;

// packages/playground/src/components/Date_range_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            d="M17 3v4M7 3v4"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            d="M3 10c0-1.886 0-2.828.586-3.414C4.172 6 5.114 6 7 6h10c1.886 0 2.828 0 3.414.586C21 7.172 21 8.114 21 10v1H3v-1Z"
        />
        <rect
            width="18"
            height="15"
            x="3"
            y="6"
            stroke="currentColor"
            stroke-width="1.2"
            rx="2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-opacity=".24"
            stroke-width="1.2"
            d="M6 15h4m4 0h4M6 18h4m4 0h4"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "dateRangeDuotoneLine",
} as DefineComponent;
</script>
