// packages/playground/src/react/components/DellDuotoneLine.tsx
import React, { SVGProps } from "react";

export function DellDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="8.4" stroke="currentColor" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m9 14.9997 6.0001-6M15 15 9 9"
            />
        </svg>
    );
}
export default DellDuotoneLine;

// packages/playground/src/components/Dell_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle
            cx="12"
            cy="12"
            r="8.4"
            stroke="currentColor"
            stroke-opacity=".24"
            stroke-width="1.2"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="1.2"
            d="m9 15 6-6m0 6L9 9"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "dellDuotoneLine",
} as DefineComponent;
</script>
