// packages/playground/src/react/components/DoneRoundDuotone.tsx
import React, { SVGProps } from "react";

export function DoneRoundDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="8" fill="currentColor" />
            <path
                stroke="currentColor"
                d="m8.5 11 2.2929 2.2929c.3905.3905 1.0237.3905 1.4142 0L19.5 6"
            />
        </svg>
    );
}
export default DoneRoundDuotone;

// packages/playground/src/components/Done_round_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="8" fill="currentColor" fill-opacity=".24" />
        <path
            stroke="currentColor"
            stroke-width="1.2"
            d="m8.5 11 2.293 2.293a1 1 0 0 0 1.414 0L19.5 6"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneRoundDuotone",
} as DefineComponent;
</script>
