// packages/playground/src/react/components/DoneFill.tsx
import React, { SVGProps } from "react";

export function DoneFill(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m19.5479 7.2665.6333-.774-.774-.6332-1.5479-1.2664-.774-.6333-.6332.774-7.786 9.5161L6.2 12.4001l-.8-.6-.6.8-1.2 1.6-.6.8.8.6 4.767 3.5751.7668.5752.607-.7419 9.6071-11.742Z"
            />
        </svg>
    );
}
export default DoneFill;

// packages/playground/src/components/Done_fill.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="m19.548 7.266.633-.774-.774-.633-1.548-1.266-.774-.633-.633.774-7.786 9.516L6.2 12.4l-.8-.6-.6.8-1.2 1.6-.6.8.8.6 4.767 3.575.767.575.607-.742 9.607-11.742Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneFill",
} as DefineComponent;
</script>
