// packages/playground/src/react/components/DoneRingRoundDuotoneLine.tsx
import React, { SVGProps } from "react";

export function DoneRingRoundDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" fill="currentColor" />
            <path
                stroke="currentColor"
                d="m9 10 3.2581 2.4436a1.0002 1.0002 0 0 0 1.3526-.1415L20 5"
            />
            <path
                stroke="currentColor"
                d="M21 12a8.9997 8.9997 0 0 1-6.107 8.5224 9.0007 9.0007 0 0 1-10.0332-3.0435 9 9 0 0 1 9.4696-14.1722"
            />
        </svg>
    );
}
export default DoneRingRoundDuotoneLine;

// packages/playground/src/components/Done_ring_round_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" fill="currentColor" fill-opacity=".24" />
        <path
            stroke="currentColor"
            stroke-width="1.2"
            d="m9 10 3.258 2.444a1 1 0 0 0 1.353-.142L20 5"
        />
        <path
            stroke="currentColor"
            stroke-width="1.2"
            d="M21 12a9 9 0 0 1-6.107 8.522A9 9 0 0 1 4.86 17.48a9 9 0 0 1 9.47-14.172"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "doneRingRoundDuotoneLine",
} as DefineComponent;
</script>
