// packages/playground/src/react/components/EditAlt.tsx
import React, { SVGProps } from "react";

export function EditAlt(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="m6 21-.189-3.0253C5.3714 10.9438 10.9553 5 18 5l-1.2173.9739A10.0789 10.0789 0 0 0 13 13.8442c0 2.1389-1.9722 3.7332-4.0636 3.285L6 16.5"
            />
        </svg>
    );
}
export default EditAlt;

// packages/playground/src/components/Edit_alt.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="m6 21-.189-3.025C5.371 10.944 10.955 5 18 5l-1.217.974A10.079 10.079 0 0 0 13 13.844a3.36 3.36 0 0 1-4.064 3.285L6 16.5"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "editAlt",
} as DefineComponent;
</script>
