// packages/playground/src/react/components/InfoAlt.tsx
import React, { SVGProps } from "react";

export function InfoAlt(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M10.5 12H12v4h2m-2-8h.01m1.5528 12.8633a8.9998 8.9998 0 0 0 7.2239-6.9153 9.001 9.001 0 0 0-1.1962-6.7837A9.0002 9.0002 0 0 0 7.1643 4.4095a9 9 0 0 0 6.3985 16.4538Z"
            />
        </svg>
    );
}
export default InfoAlt;

// packages/playground/src/components/Info_alt.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-linejoin="round"
            stroke-width="2"
            d="M10.5 12H12v4h2m-2-8h.01m1.553 12.863a9 9 0 0 0 7.224-6.915 9.001 9.001 0 0 0-1.196-6.784A9 9 0 0 0 7.163 4.41a9 9 0 0 0 6.399 16.453Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "infoAlt",
} as DefineComponent;
</script>
