// packages/playground/src/react/components/JumpTimeDuotone.tsx
import React, { SVGProps } from "react";

export function JumpTimeDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="m17.3292 6.3416-5.1056 10.2112c-.0921.1842-.3551.1842-.4472 0L6.6708 6.3416c-.2149-.4297.241-.8857.6708-.6708l4.2112 2.1056a.9999.9999 0 0 0 .8944 0l4.2112-2.1056c.4297-.2149.8857.241.6708.6708Z"
            />
            <path stroke="currentColor" d="M14.5 17.5h4m-13 0h4" />
        </svg>
    );
}
export default JumpTimeDuotone;

// packages/playground/src/components/Jump_time_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-opacity=".24"
            d="m17.33 6.342-5.106 10.21a.25.25 0 0 1-.448 0L6.671 6.343a.5.5 0 0 1 .67-.671l4.212 2.105a1 1 0 0 0 .894 0l4.211-2.105a.5.5 0 0 1 .671.67Z"
        />
        <path stroke="currentColor" d="M14.5 17.5h4m-13 0h4" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "jumpTimeDuotone",
} as DefineComponent;
</script>
