// packages/playground/src/react/components/MoneyDuotone.tsx
import React, { SVGProps } from "react";

export function MoneyDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="M3 10c0-1.8856 0-2.8284.5858-3.4142C4.1716 6 5.1144 6 7 6h10c1.8856 0 2.8284 0 3.4142.5858C21 7.1716 21 8.1144 21 10v4c0 1.8856 0 2.8284-.5858 3.4142C19.8284 18 18.8856 18 17 18H7c-1.8856 0-2.8284 0-3.4142-.5858C3 16.8284 3 15.8856 3 14v-4Z"
            />
            <circle cx="12" cy="12" r="2" fill="currentColor" />
            <rect
                width="3"
                height="1"
                x="5"
                y="8"
                fill="currentColor"
                rx=".5"
            />
            <rect
                width="3"
                height="1"
                x="16"
                y="15"
                fill="currentColor"
                rx=".5"
            />
        </svg>
    );
}
export default MoneyDuotone;

// packages/playground/src/components/Money_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-opacity=".24"
            d="M3 10c0-1.886 0-2.828.586-3.414C4.172 6 5.114 6 7 6h10c1.886 0 2.828 0 3.414.586C21 7.172 21 8.114 21 10v4c0 1.886 0 2.828-.586 3.414C19.828 18 18.886 18 17 18H7c-1.886 0-2.828 0-3.414-.586C3 16.828 3 15.886 3 14v-4Z"
        />
        <circle cx="12" cy="12" r="2" fill="currentColor" />
        <rect width="3" height="1" x="5" y="8" fill="currentColor" rx=".5" />
        <rect width="3" height="1" x="16" y="15" fill="currentColor" rx=".5" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "moneyDuotone",
} as DefineComponent;
</script>
