// packages/playground/src/react/components/PieChart.tsx
import React, { SVGProps } from "react";

export function PieChart(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="9" stroke="currentColor" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12 12h9m-9-9v8.9379c0 .0398.0158.0779.0439.106L18 18"
            />
        </svg>
    );
}
export default PieChart;

// packages/playground/src/components/Pie_chart.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="2" />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M12 12h9m-9-9v8.938c0 .04.016.078.044.106L18 18"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "pieChart",
} as DefineComponent;
</script>
