// packages/playground/src/react/components/SearchAltFill.tsx
import React, { SVGProps } from "react";

export function SearchAltFill(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="M11 18c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7Zm0-12a5.0001 5.0001 0 0 0-5 5c0 .5523.4477 1 1 1s1-.4477 1-1a2.9998 2.9998 0 0 1 3-3c.5523 0 1-.4477 1-1s-.4477-1-1-1Z"
            />
            <path stroke="currentColor" d="m20 20-2-2" />
        </svg>
    );
}
export default SearchAltFill;

// packages/playground/src/components/Search_alt_fill.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-rule="evenodd"
            d="M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm0-12a5 5 0 0 0-5 5 1 1 0 1 0 2 0 3 3 0 0 1 3-3 1 1 0 1 0 0-2Z"
            clip-rule="evenodd"
        />
        <path stroke="currentColor" stroke-width="2" d="m20 20-2-2" />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "searchAltFill",
} as DefineComponent;
</script>
