// packages/playground/src/react/components/Sun.tsx
import React, { SVGProps } from "react";

export function Sun(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="3" stroke="currentColor" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12 5V3m0 18v-2m4.9498-11.9497L18.364 5.636M5.636 18.364l1.4143-1.4142M19 12h2M3 12h2m11.9498 4.9497 1.4142 1.4143M5.636 5.636l1.4143 1.4142"
            />
        </svg>
    );
}
export default Sun;

// packages/playground/src/components/Sun.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="2" />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M12 5V3m0 18v-2m4.95-11.95 1.414-1.414M5.636 18.364 7.05 16.95M19 12h2M3 12h2m11.95 4.95 1.414 1.414M5.636 5.636 7.05 7.05"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "sun",
} as DefineComponent;
</script>
