// packages/playground/src/react/components/SunLight.tsx
import React, { SVGProps } from "react";

export function Sunlight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="12" r="4" stroke="currentColor" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12 8V4m0 16v-4M9.1716 9.1716 6.343 6.343m11.3138 11.3139-2.8284-2.8285M16 12h4M4 12h4m6.8283-2.8284 2.8284-2.8285M6.3432 17.6569l2.8284-2.8285"
            />
        </svg>
    );
}
export default Sunlight;

// packages/playground/src/components/Sun_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="12" r="3.5" stroke="currentColor" />
        <path
            fill="none"
            stroke="currentColor"
            d="M12 5V3m0 18v-2m4.95-11.95 1.414-1.414M5.636 18.364 7.05 16.95M19 12h2M3 12h2m11.95 4.95 1.414 1.414M5.636 5.636 7.05 7.05"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "sunLight",
} as DefineComponent;
</script>
