// packages/playground/src/react/components/TransferLongTop.tsx
import React, { SVGProps } from "react";

export function TransferLongTop(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M10 22V10H6.4348c-.1708 0-.263-.2004-.1518-.3302L12 3l5.717 6.6698c.1112.1298.019.3302-.1518.3302H14v12"
            />
        </svg>
    );
}
export default TransferLongTop;

// packages/playground/src/components/Transfer_long_top.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M10 22V10H6.435a.2.2 0 0 1-.152-.33L12 3l5.717 6.67a.2.2 0 0 1-.152.33H14v12"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "transferLongTop",
} as DefineComponent;
</script>
