// packages/playground/src/react/components/TransferDownLight.tsx
import React, { SVGProps } from "react";

export function TransferDownLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M9 5v7H5.4828c-.1781 0-.2674.2154-.1414.3414L12 19l6.6586-6.6586c.126-.126.0367-.3414-.1414-.3414H15V5"
            />
        </svg>
    );
}
export default TransferDownLight;

// packages/playground/src/components/Transfer_down_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M9 5v7H5.483a.2.2 0 0 0-.142.341L12 19l6.659-6.659a.2.2 0 0 0-.142-.341H15V5"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "transferDownLight",
} as DefineComponent;
</script>
