// packages/playground/src/react/components/TransferLongRightLight.tsx
import React, { SVGProps } from "react";

export function TransferLongRightLight(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M2 10h12V6.4348c0-.1708.2004-.263.3302-.1518L21 12l-6.6698 5.717c-.1298.1112-.3302.019-.3302-.1518V14H2"
            />
        </svg>
    );
}
export default TransferLongRightLight;

// packages/playground/src/components/Transfer_long_right_light.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M2 10h12V6.435a.2.2 0 0 1 .33-.152L21 12l-6.67 5.717a.2.2 0 0 1-.33-.152V14H2"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "transferLongRightLight",
} as DefineComponent;
</script>
