// packages/playground/src/react/components/TumerDuotone.tsx
import React, { SVGProps } from "react";

export function TumerDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="13" r="8" fill="currentColor" />
            <path stroke="currentColor" d="M12 13V8" />
            <path
                fill="currentColor"
                d="M20.3536 5.3536a.5001.5001 0 0 0-.7071-.7072l.7071.7072Zm-1.5 1.5 1.5-1.5-.7071-.7072-1.5001 1.5.7072.7072Z"
            />
            <path
                stroke="currentColor"
                d="M10.0681 3.3706c.114-.1063.3651-.2003.7144-.2673C11.1318 3.0363 11.5597 3 12 3s.8682.0363 1.2175.1033c.3493.067.6004.161.7144.2673"
            />
        </svg>
    );
}
export default TumerDuotone;

// packages/playground/src/components/Tumer_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="13" r="8" fill="currentColor" fill-opacity=".24" />
        <path stroke="currentColor" stroke-width="1.2" d="M12 13V8" />
        <path
            fill="currentColor"
            d="M20.354 5.354a.5.5 0 0 0-.707-.708l.707.708Zm-1.5 1.5 1.5-1.5-.707-.708-1.5 1.5.707.708Z"
        />
        <path
            stroke="currentColor"
            stroke-width="1.2"
            d="M10.068 3.37c.114-.106.365-.2.714-.267C11.132 3.036 11.56 3 12 3s.868.036 1.218.103c.349.067.6.161.714.268"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "tumerDuotone",
} as DefineComponent;
</script>
