// packages/playground/src/react/components/UserCicrleDuotone.tsx
import React, { SVGProps } from "react";

export function UserCicrleDuotone(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                d="M3 12c0-4.9706 4.0294-9 9-9s9 4.0294 9 9-4.0294 9-9 9-9-4.0294-9-9Z"
            />
            <circle cx="12" cy="10" r="4" fill="currentColor" />
            <path
                fill="currentColor"
                d="M18.2209 18.2462a.2386.2386 0 0 1-.0414.297C16.5674 20.0662 14.3928 21 12 21c-2.3927 0-4.5674-.9337-6.1794-2.4567a.2387.2387 0 0 1-.0414-.297C6.9434 16.318 9.2922 15 12 15c2.7078 0 5.0566 1.3179 6.2208 3.2462Z"
            />
        </svg>
    );
}
export default UserCicrleDuotone;

// packages/playground/src/components/User_cicrle_duotone.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="currentColor"
            fill-opacity=".24"
            d="M3 12a9 9 0 1 1 18 0 9 9 0 0 1-18 0Z"
        />
        <circle cx="12" cy="10" r="4" fill="currentColor" />
        <path
            fill="currentColor"
            fill-rule="evenodd"
            d="M18.22 18.246a.239.239 0 0 1-.04.297A8.969 8.969 0 0 1 12 21a8.969 8.969 0 0 1-6.18-2.457.239.239 0 0 1-.04-.297C6.942 16.318 9.291 15 12 15c2.708 0 5.057 1.318 6.22 3.246Z"
            clip-rule="evenodd"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "userCicrleDuotone",
} as DefineComponent;
</script>
