// packages/playground/src/react/components/UserAlt.tsx
import React, { SVGProps } from "react";

export function UserAlt(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <circle cx="12" cy="7" r="4" stroke="currentColor" />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M5.3379 18.3206C5.9989 15.5269 8.7717 14 11.6426 14h.7148c2.8709 0 5.6436 1.5269 6.3047 4.3206.1279.5405.2296 1.1062.2868 1.681.0547.5496-.3966.9984-.9489.9984H6c-.5523 0-1.0036-.4488-.9489-.9984.0572-.5748.1589-1.1405.2868-1.681Z"
            />
        </svg>
    );
}
export default UserAlt;

// packages/playground/src/components/User_alt.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <circle cx="12" cy="7" r="4" stroke="currentColor" stroke-width="2" />
        <path
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            d="M5.338 18.32c.66-2.793 3.434-4.32 6.305-4.32h.714c2.871 0 5.644 1.527 6.305 4.32.128.541.23 1.107.287 1.682.055.55-.397.998-.949.998H6c-.552 0-1.004-.449-.949-.998.057-.575.159-1.14.287-1.681Z"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "userAlt",
} as DefineComponent;
</script>
