// packages/playground/src/react/components/ViewHorizontDuotoneLine.tsx
import React, { SVGProps } from "react";

export function ViewHorizontDuotoneLine(props: SVGProps<SVGSVGElement>) {
    return (
        <svg
            fill="currentColor"
            viewBox="0 0 24 24"
            width="1em"
            height="1em"
            {...props}
        >
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M12.4208 7.6022a9.5002 9.5002 0 0 1-.1358 9.0464"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M14.5 5.5c-2.7811 3.7081-9.8591 6.1272-10.8773 6.4605a.0488.0488 0 0 0-.0046.0918c1.001.446 8.0965 3.6623 10.8819 6.4477"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M13.233 14.4891a2.4993 2.4993 0 0 1-1.8991-.6252 2.5 2.5 0 0 1 1.8062-4.36"
            />
            <path
                fill="currentColor"
                stroke="currentColor"
                d="M16.5 12h4m-4-2.5 4-1.5m-4 6.5 4 1.5"
            />
        </svg>
    );
}
export default ViewHorizontDuotoneLine;

// packages/playground/src/components/View_horizont_duotone_line.vue
<template>
    <svg
        fill="currentColor"
        viewBox="0 0 24 24"
        width="1em"
        height="1em"
        v-bind="$attrs"
    >
        <path
            fill="none"
            stroke="currentColor"
            d="M12.42 7.602a9.5 9.5 0 0 1-.135 9.047"
        />
        <path
            fill="none"
            stroke="currentColor"
            d="M14.5 5.5c-2.781 3.708-9.86 6.127-10.877 6.46a.049.049 0 0 0-.005.092c1.001.446 8.097 3.663 10.882 6.448"
        />
        <path
            fill="none"
            stroke="currentColor"
            d="M13.233 14.49a2.5 2.5 0 0 1-1.9-.626 2.5 2.5 0 0 1 1.807-4.36"
        />
        <path
            fill="none"
            stroke="currentColor"
            stroke-opacity=".24"
            d="M16.5 12h4m-4-2.5 4-1.5m-4 6.5 4 1.5"
        />
    </svg>
</template>

<script lang="ts">
import type { DefineComponent } from "vue";
export default {
    name: "viewHorizontDuotoneLine",
} as DefineComponent;
</script>
